options:
  merge-default-rules: false

files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'src/libs/**/*.*'
    - 'src/sass/generated/**/*.*'
rules:
  # Extends
  indentation:
    - 1
    - size: tab

  nesting-depth:
    - 2
    - max-depth: 4

  quotes: 1
  leading-zero: 
    - 1
    - include: false
  clean-import-paths: 
    - 2
    - filename-extension: false

  declarations-before-nesting: 1
  shorthand-values: 1

  no-duplicate-properties: 2
  no-misspelled-properties: 2
  no-invalid-hex: 1
  no-empty-rulesets: 1
  no-css-comments: 2
  no-transition-all: 1


  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

   # Final Items
  final-newline: 1




  property-sort-order:
    - 1
    -
      order:
        - content

        - position
        - top
        - right
        - bottom
        - left
        - z-index

        - order
        - flex
        - flex-grow
        - flex-shrink
        - flex-basis
        - align-self
        

        - display

        - flex-direction
        - flex-wrap
        - justify-content
        - align-content
        - align-items

        - float

        - width
        - max-width
        - min-width
        - height
        - max-height
        - min-height

        - object-fit
        - object-position
        
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left

        - margin-collapse
        - margin-top-collapse
        - margin-right-collapse
        - margin-bottom-collapse
        - margin-left-collapse

        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left

        - overflow
        - overflow-x
        - overflow-y

        - clip

        - clear

        - font
        - font-family
        - font-size
        - font-smoothing
        - osx-font-smoothing
        - font-style
        - font-weight

        - hyphens
        - line-height
        - letter-spacing
        - word-spacing
        - text-align
        - text-decoration
        - text-indent
        - text-overflow
        - text-rendering
        - text-size-adjust
        - text-shadow
        - text-transform
        - word-break
        - word-wrap
        - white-space
        - vertical-align

        - list-style
        - list-style-type
        - list-style-position
        - list-style-image

        - pointer-events
        - cursor

        - color

        - fill
        
        - background
        - background-color
        - background-image
        - background-size
        - background-position
        - background-repeat
        - background-clip
        - background-attachment


        - border
        - border-collapse
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-color
        - border-image
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - border-spacing
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - border-top-left-radius
        - border-radius-topright
        - border-radius-bottomright
        - border-radius-bottomleft
        - border-radius-topleft

        - outline
        - outline-offset

        - box-shadow
        - box-sizing
        - table-layout

        - opacity
        - visibility
        - filter
        - zoom
        - transform
        - transform-origin
        - will-change


        - animation
        - animation-delay
        - animation-duration
        - animation-iteration-count
        - animation-name
        - animation-play-state
        - animation-timing-function
        - animation-fill-mode

        - transition
        - transition-delay
        - transition-duration
        - transition-property
        - transition-timing-function
        - backface-visibility

